#!/usr/bin/env bash

set -e

COMMANDS=$(ls -1 scripts | sed -e 's/\.sh$//' | xargs)

case ${COMMANDS} in
  *${1:-unset}*)
    CMD=$1
    shift
    {
      scripts/${CMD}.sh $@ && \
      echo "🐝 Command '$CMD' successful."
    } || {
      echo "🚨 Command '$CMD' unsuccessful."
      exit 1
    }
    ;;
  *)
    echo "Usage: btw [$(echo ${COMMANDS} | sed -e 's/ /|/g')]"
    exit 1
esac
